services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - /home/ubuntu/postgres/postgres-data:/var/lib/postgresql/data
  spring:
    image: rig14/matkarajad:latest
    container_name: web-project
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /home/ubuntu/web-project/application.properties:/app/application.properties
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana/
    volumes:
      - ./grafana/:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'